### ISSUE TITLE
Compatibility with Apple Silicon M1

### ISSUE THREAD

**Issue by melalj** [plaid/pattern#164]
It seems that there are no arm64-64 binaries for node-saas.
I keep getting this error when I do a `make start`

Is there any recommendations on how to fix this?

```
=> ERROR [5/7] RUN npm ci                                                11.9s
------
 > [5/7] RUN npm ci:
#8 9.959
#8 9.959 > core-js@2.6.9 postinstall /opt/client/node_modules/babel-runtime/node_modules/core-js
#8 9.959 > node scripts/postinstall || echo "ignore"
#8 9.959
#8 10.02 Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
#8 10.02
#8 10.02 The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
#8 10.02 > https://opencollective.com/core-js
#8 10.02 > https://www.patreon.com/zloirock
#8 10.02
#8 10.02 Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
#8 10.02
#8 10.04
#8 10.04 > ejs@2.7.4 postinstall /opt/client/node_modules/ejs
#8 10.04 > node ./postinstall.js
#8 10.04
#8 10.08 Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)
#8 10.08
#8 10.17
#8 10.17 > fsevents@1.2.13 install /opt/client/node_modules/webpack-dev-server/node_modules/fsevents
#8 10.17 > node install.js
#8 10.17
#8 10.21
#8 10.21 Skipping 'fsevents' build as platform linux is not supported
#8 10.23
#8 10.23 > fsevents@1.2.13 install /opt/client/node_modules/watchpack-chokidar2/node_modules/fsevents
#8 10.23 > node install.js
#8 10.23
#8 10.29
#8 10.29 Skipping 'fsevents' build as platform linux is not supported
#8 10.41
#8 10.41 > core-js@3.15.0 postinstall /opt/client/node_modules/core-js
#8 10.41 > node -e "try{require('./postinstall')}catch(e){}"
#8 10.41
#8 10.45 Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
#8 10.45
#8 10.45 The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
#8 10.45 > https://opencollective.com/core-js
#8 10.45 > https://www.patreon.com/zloirock
#8 10.45
#8 10.45 Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
#8 10.45
#8 10.63
#8 10.63 > core-js-pure@3.15.0 postinstall /opt/client/node_modules/core-js-pure
#8 10.63 > node -e "try{require('./postinstall')}catch(e){}"
#8 10.63
#8 10.67 Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
#8 10.67
#8 10.67 The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
#8 10.67 > https://opencollective.com/core-js
#8 10.67 > https://www.patreon.com/zloirock
#8 10.67
#8 10.67 Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
#8 10.67
#8 10.75
#8 10.75 > node-sass@4.14.1 install /opt/client/node_modules/node-sass
#8 10.75 > node scripts/install.js
#8 10.75
#8 11.02 Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm64-64_binding.node
#8 11.17 Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm64-64_binding.node":
#8 11.17
#8 11.17 HTTP error 404 Not Found
#8 11.17
#8 11.17 Hint: If github.com is not accessible in your location
#8 11.17       try setting a proxy via HTTP_PROXY, e.g.
#8 11.17
#8 11.17       export HTTP_PROXY=http://example.com:1234
#8 11.17
#8 11.17 or configure npm proxy via
#8 11.17
#8 11.17       npm config set proxy http://example.com:8080
#8 11.19
#8 11.19 > node-sass@4.14.1 postinstall /opt/client/node_modules/node-sass
#8 11.19 > node scripts/build.js
#8 11.19
#8 11.26 Building: /usr/local/bin/node /opt/client/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
#8 11.31 gyp info it worked if it ends with ok
#8 11.32 gyp verb cli [ '/usr/local/bin/node',
#8 11.32 gyp verb cli   '/opt/client/node_modules/node-gyp/bin/node-gyp.js',
#8 11.32 gyp verb cli   'rebuild',
#8 11.32 gyp verb cli   '--verbose',
#8 11.32 gyp verb cli   '--libsass_ext=',
#8 11.32 gyp verb cli   '--libsass_cflags=',
#8 11.32 gyp verb cli   '--libsass_ldflags=',
#8 11.32 gyp verb cli   '--libsass_library=' ]
#8 11.32 gyp info using node-gyp@3.8.0
#8 11.32 gyp info using node@10.15.3 | linux | arm64
#8 11.32 gyp verb command rebuild []
#8 11.32 gyp verb command clean []
#8 11.32 gyp verb clean removing "build" directory
#8 11.32 gyp verb command configure []
#8 11.33 gyp verb check python checking for Python executable "python2" in the PATH
#8 11.33 gyp verb `which` failed Error: not found: python2
#8 11.33 gyp verb `which` failed     at getNotFoundError (/opt/client/node_modules/which/which.js:13:12)
#8 11.33 gyp verb `which` failed     at F (/opt/client/node_modules/which/which.js:68:19)
#8 11.33 gyp verb `which` failed     at E (/opt/client/node_modules/which/which.js:80:29)
#8 11.33 gyp verb `which` failed     at /opt/client/node_modules/which/which.js:89:16
#8 11.33 gyp verb `which` failed     at /opt/client/node_modules/isexe/index.js:42:5
#8 11.33 gyp verb `which` failed     at /opt/client/node_modules/isexe/mode.js:8:5
#8 11.33 gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
#8 11.33 gyp verb `which` failed  python2 { Error: not found: python2
#8 11.33 gyp verb `which` failed     at getNotFoundError (/opt/client/node_modules/which/which.js:13:12)
#8 11.33 gyp verb `which` failed     at F (/opt/client/node_modules/which/which.js:68:19)
#8 11.33 gyp verb `which` failed     at E (/opt/client/node_modules/which/which.js:80:29)
#8 11.33 gyp verb `which` failed     at /opt/client/node_modules/which/which.js:89:16
#8 11.33 gyp verb `which` failed     at /opt/client/node_modules/isexe/index.js:42:5
#8 11.33 gyp verb `which` failed     at /opt/client/node_modules/isexe/mode.js:8:5
#8 11.33 gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
#8 11.33 gyp verb `which` failed   stack:
#8 11.33 gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (/opt/client/node_modules/which/which.js:13:12)\n    at F (/opt/client/node_modules/which/which.js:68:19)\n    at E (/opt/client/node_modules/which/which.js:80:29)\n    at /opt/client/node_modules/which/which.js:89:16\n    at /opt/client/node_modules/isexe/index.js:42:5\n    at /opt/client/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
#8 11.33 gyp verb `which` failed   code: 'ENOENT' }
#8 11.33 gyp verb check python checking for Python executable "python" in the PATH
#8 11.33 gyp verb `which` failed Error: not found: python
#8 11.33 gyp verb `which` failed     at getNotFoundError (/opt/client/node_modules/which/which.js:13:12)
#8 11.33 gyp verb `which` failed     at F (/opt/client/node_modules/which/which.js:68:19)
#8 11.33 gyp verb `which` failed     at E (/opt/client/node_modules/which/which.js:80:29)
#8 11.33 gyp verb `which` failed     at /opt/client/node_modules/which/which.js:89:16
#8 11.33 gyp verb `which` failed     at /opt/client/node_modules/isexe/index.js:42:5
#8 11.33 gyp verb `which` failed     at /opt/client/node_modules/isexe/mode.js:8:5
#8 11.33 gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
#8 11.33 gyp verb `which` failed  python { Error: not found: python
#8 11.33 gyp verb `which` failed     at getNotFoundError (/opt/client/node_modules/which/which.js:13:12)
#8 11.33 gyp verb `which` failed     at F (/opt/client/node_modules/which/which.js:68:19)
#8 11.33 gyp verb `which` failed     at E (/opt/client/node_modules/which/which.js:80:29)
#8 11.33 gyp verb `which` failed     at /opt/client/node_modules/which/which.js:89:16
#8 11.33 gyp verb `which` failed     at /opt/client/node_modules/isexe/index.js:42:5
#8 11.33 gyp verb `which` failed     at /opt/client/node_modules/isexe/mode.js:8:5
#8 11.33 gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
#8 11.33 gyp verb `which` failed   stack:
#8 11.33 gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (/opt/client/node_modules/which/which.js:13:12)\n    at F (/opt/client/node_modules/which/which.js:68:19)\n    at E (/opt/client/node_modules/which/which.js:80:29)\n    at /opt/client/node_modules/which/which.js:89:16\n    at /opt/client/node_modules/isexe/index.js:42:5\n    at /opt/client/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
#8 11.33 gyp verb `which` failed   code: 'ENOENT' }
#8 11.33 gyp ERR! configure error
#8 11.33 gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
#8 11.33 gyp ERR! stack     at PythonFinder.failNoPython (/opt/client/node_modules/node-gyp/lib/configure.js:484:19)
#8 11.33 gyp ERR! stack     at PythonFinder.<anonymous> (/opt/client/node_modules/node-gyp/lib/configure.js:406:16)
#8 11.33 gyp ERR! stack     at F (/opt/client/node_modules/which/which.js:68:16)
#8 11.33 gyp ERR! stack     at E (/opt/client/node_modules/which/which.js:80:29)
#8 11.33 gyp ERR! stack     at /opt/client/node_modules/which/which.js:89:16
#8 11.33 gyp ERR! stack     at /opt/client/node_modules/isexe/index.js:42:5
#8 11.33 gyp ERR! stack     at /opt/client/node_modules/isexe/mode.js:8:5
#8 11.33 gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
#8 11.33 gyp ERR! System Linux 5.10.25-linuxkit
#8 11.33 gyp ERR! command "/usr/local/bin/node" "/opt/client/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#8 11.33 gyp ERR! cwd /opt/client/node_modules/node-sass
#8 11.33 gyp ERR! node -v v10.15.3
#8 11.33 gyp ERR! node-gyp -v v3.8.0
#8 11.33 gyp ERR! not ok
#8 11.33 Build failed with error code: 1
#8 11.34 npm ERR! code ELIFECYCLE
#8 11.34 npm ERR! errno 1
#8 11.34 npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
#8 11.34 npm ERR! Exit status 1
#8 11.34 npm ERR!
#8 11.34 npm ERR! Failed at the node-sass@4.14.1 postinstall script.
#8 11.34 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#8 11.39
#8 11.39 npm ERR! A complete log of this run can be found in:
#8 11.39 npm ERR!     /root/.npm/_logs/2021-09-22T22_13_00_043Z-debug.log
------
executor failed running [/bin/sh -c npm ci]: exit code: 1
ERROR: Service 'client' failed to build : Build failed
make: *** [start] Error 1
```

**Comment by lindawoo-plaid** [comment]
could you go into the client folder and run `npm uninstall node-sass` and then `npm install sass`

and then another make start.  hopefully this will solve your problem.

**Comment by lindawoo-plaid** [comment]
@melalj , Has your issue been solved?  If so, can I close this issue?
